"""initial schema

Revision ID: a3e9c1bf798e
Revises:
Create Date: 2026-07-12 12:07:54.559540
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a3e9c1bf798e"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("discord_user_id", sa.BigInteger(), nullable=False),
        sa.Column("platform", sa.String(length=16), nullable=False),
        sa.Column("platform_user_id", sa.String(length=64), nullable=False),
        sa.Column("platform_username", sa.String(length=128), nullable=False),
        sa.Column("extra_ids", sa.JSON(), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("verify_token", sa.String(length=32), nullable=True),
        sa.Column("verify_expires_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("discord_user_id", "platform", name="uq_link_user_platform"),
        sa.UniqueConstraint("platform", "platform_user_id", name="uq_link_platform_account"),
    )
    with op.batch_alter_table("account_links", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_account_links_discord_user_id"), ["discord_user_id"], unique=False
        )

    op.create_table(
        "catalog_boxes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("platform", sa.String(length=16), nullable=False),
        sa.Column("platform_ref", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("name_normalized", sa.String(length=128), nullable=False),
        sa.Column("os", sa.String(length=32), nullable=True),
        sa.Column("difficulty", sa.String(length=32), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("retired", sa.Boolean(), nullable=False),
        sa.Column("stars", sa.Float(), nullable=True),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("ippsec_video_id", sa.String(length=16), nullable=True),
        sa.Column("release_date", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("platform", "platform_ref", name="uq_box_platform_ref"),
    )
    with op.batch_alter_table("catalog_boxes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_catalog_boxes_name_normalized"), ["name_normalized"], unique=False
        )

    op.create_table(
        "guilds",
        sa.Column("guild_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("mod_role_id", sa.BigInteger(), nullable=True),
        sa.Column("mod_channel_id", sa.BigInteger(), nullable=True),
        sa.Column("announce_channel_id", sa.BigInteger(), nullable=True),
        sa.Column("recap_channel_id", sa.BigInteger(), nullable=True),
        sa.Column("recap_enabled", sa.Boolean(), nullable=False),
        sa.Column("require_verified", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("guild_id"),
    )
    op.create_table(
        "kv",
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "claims",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("discord_user_id", sa.BigInteger(), nullable=False),
        sa.Column("platform_key", sa.String(length=32), nullable=False),
        sa.Column("item_name", sa.String(length=256), nullable=False),
        sa.Column("difficulty", sa.String(length=32), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("proof_url", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("mod_message_id", sa.BigInteger(), nullable=True),
        sa.Column("reviewed_by", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["guild_id"], ["guilds.guild_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("claims", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_claims_discord_user_id"), ["discord_user_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_claims_guild_id"), ["guild_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_claims_status"), ["status"], unique=False)

    op.create_table(
        "guild_members",
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("discord_user_id", sa.BigInteger(), nullable=False),
        sa.Column("hidden", sa.Boolean(), nullable=False),
        sa.Column("joined_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["guild_id"], ["guilds.guild_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("guild_id", "discord_user_id"),
    )
    op.create_table(
        "snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("link_id", sa.Integer(), nullable=False),
        sa.Column("taken_at", sa.DateTime(), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.Column("counters", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["link_id"], ["account_links.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("snapshots", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_snapshots_link_id"), ["link_id"], unique=False)
        batch_op.create_index("ix_snapshots_link_taken", ["link_id", "taken_at"], unique=False)

    op.create_table(
        "solves",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("link_id", sa.Integer(), nullable=False),
        sa.Column("platform", sa.String(length=16), nullable=False),
        sa.Column("item_ref", sa.String(length=128), nullable=False),
        sa.Column("item_name", sa.String(length=256), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("solved_at", sa.DateTime(), nullable=True),
        sa.Column("first_blood", sa.Boolean(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(), nullable=False),
        sa.Column("backfilled", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["link_id"], ["account_links.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("link_id", "item_ref", "kind", name="uq_solve_link_item_kind"),
    )
    with op.batch_alter_table("solves", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_solves_link_id"), ["link_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("solves", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_solves_link_id"))

    op.drop_table("solves")
    with op.batch_alter_table("snapshots", schema=None) as batch_op:
        batch_op.drop_index("ix_snapshots_link_taken")
        batch_op.drop_index(batch_op.f("ix_snapshots_link_id"))

    op.drop_table("snapshots")
    op.drop_table("guild_members")
    with op.batch_alter_table("claims", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_claims_status"))
        batch_op.drop_index(batch_op.f("ix_claims_guild_id"))
        batch_op.drop_index(batch_op.f("ix_claims_discord_user_id"))

    op.drop_table("claims")
    op.drop_table("kv")
    op.drop_table("guilds")
    with op.batch_alter_table("catalog_boxes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_catalog_boxes_name_normalized"))

    op.drop_table("catalog_boxes")
    with op.batch_alter_table("account_links", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_account_links_discord_user_id"))

    op.drop_table("account_links")
    # ### end Alembic commands ###
